name: Nodejs Project

on:
  push:
    branches:
    - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Clone repository
      run: git clone https://github.com/username/repo-name.git

    - name: Install Dependencies
      run: cd repo-name && npm install

    - name: Deploy Node.js Application
      run: |
        cd repo-name
        aws ec2 run-instances \
          --image-id ami-0abcdef1234567890 \
          --count 1 \
          --instance-type t2.micro \
          --key-name your-ec2-key-name \
          --security-group-ids sg-0abc12345def67890 \
          --subnet-id subnet-0abcdef1234567890 \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=NodejsApp}]'

    - name: Confirm Deployment
      run: aws ec2 describe-instances --query "Reservations[*].Instances[*].State.Name" --output text
